server:
  port: 8082
  servlet:
    context-path: /account

spring:
  application:
    name: account
  datasource:
    url: jdbc:mysql://localhost:3306/account
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
